
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A AD AM AMD AND AT D EQUAL JEQ JGE JGT JLE JLT JMP JNE LPAREN M MD MINUS NOT NUMBER OR PLUS RPAREN SEMI SYMBOLstatements : statement statementsstatements : emptyempty : statement : p_instructionstatement : a_instructionstatement : l_instruction\na_instruction : AT NUMBER\n\na_instruction : AT SYMBOL\n\nl_instruction : LPAREN SYMBOL RPAREN\np_instruction : dest EQUAL comp SEMI jumpp_instruction : dest EQUAL compp_instruction : comp SEMI jumpp_instruction : comp\ndest : SYMBOL\n\ncomp : SYMBOL\n\ncomp : NUMBER\n\njump : SYMBOL\n'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,8,10,11,13,16,17,19,20,21,22,23,25,],[-3,0,-3,-2,-4,-5,-6,-13,-16,-15,-1,-7,-8,-11,-15,-12,-17,-9,-10,]),'AT':([0,2,4,5,6,8,10,11,16,17,19,20,21,22,23,25,],[9,9,-4,-5,-6,-13,-16,-15,-7,-8,-11,-15,-12,-17,-9,-10,]),'LPAREN':([0,2,4,5,6,8,10,11,16,17,19,20,21,22,23,25,],[12,12,-4,-5,-6,-13,-16,-15,-7,-8,-11,-15,-12,-17,-9,-10,]),'SYMBOL':([0,2,4,5,6,8,9,10,11,12,14,15,16,17,19,20,21,22,23,24,25,],[11,11,-4,-5,-6,-13,17,-16,-15,18,20,22,-7,-8,-11,-15,-12,-17,-9,22,-10,]),'NUMBER':([0,2,4,5,6,8,9,10,11,14,16,17,19,20,21,22,23,25,],[10,10,-4,-5,-6,-13,16,-16,-15,10,-7,-8,-11,-15,-12,-17,-9,-10,]),'EQUAL':([7,11,],[14,-14,]),'SEMI':([8,10,11,19,20,],[15,-16,-15,24,-15,]),'RPAREN':([18,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,2,],[1,13,]),'statement':([0,2,],[2,2,]),'empty':([0,2,],[3,3,]),'p_instruction':([0,2,],[4,4,]),'a_instruction':([0,2,],[5,5,]),'l_instruction':([0,2,],[6,6,]),'dest':([0,2,],[7,7,]),'comp':([0,2,14,],[8,8,19,]),'jump':([15,24,],[21,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statement statements','statements',2,'p_statements_1','asm.py',139),
  ('statements -> empty','statements',1,'p_statements_2','asm.py',142),
  ('empty -> <empty>','empty',0,'p_empty_1','asm.py',146),
  ('statement -> p_instruction','statement',1,'p_statement_1','asm.py',149),
  ('statement -> a_instruction','statement',1,'p_statement_2','asm.py',153),
  ('statement -> l_instruction','statement',1,'p_statement_3','asm.py',157),
  ('a_instruction -> AT NUMBER','a_instruction',2,'p_a_instruction_1','asm.py',163),
  ('a_instruction -> AT SYMBOL','a_instruction',2,'p_a_instruction_2','asm.py',169),
  ('l_instruction -> LPAREN SYMBOL RPAREN','l_instruction',3,'p_l_instruction','asm.py',176),
  ('p_instruction -> dest EQUAL comp SEMI jump','p_instruction',5,'p_p_instruction_1','asm.py',184),
  ('p_instruction -> dest EQUAL comp','p_instruction',3,'p_p_instruction_2','asm.py',189),
  ('p_instruction -> comp SEMI jump','p_instruction',3,'p_p_instruction_3','asm.py',194),
  ('p_instruction -> comp','p_instruction',1,'p_p_instruction_4','asm.py',199),
  ('dest -> SYMBOL','dest',1,'p_dest','asm.py',205),
  ('comp -> SYMBOL','comp',1,'p_comp_1','asm.py',211),
  ('comp -> NUMBER','comp',1,'p_comp_2','asm.py',217),
  ('jump -> SYMBOL','jump',1,'p_jump','asm.py',224),
]
