
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUAL LPAREN MINUS NUMBER PLUS PRINT RPAREN SYMBOL TIMESstatements : statement statementsstatements : emptyempty : statement : p_statementstatement : a_statementp_statement : PRINT expressiona_statement : SYMBOL EQUAL expressionexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : numfactor : MINUS numfactor : LPAREN expression RPARENnum : NUMBERnum : SYMBOL'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,8,9,10,12,13,15,16,22,24,25,26,27,28,29,],[-3,0,-3,-2,-4,-5,-1,-6,-10,-13,-14,-17,-18,-15,-7,-8,-9,-11,-12,-16,]),'PRINT':([0,2,4,5,9,10,12,13,15,16,22,24,25,26,27,28,29,],[6,6,-4,-5,-6,-10,-13,-14,-17,-18,-15,-7,-8,-9,-11,-12,-16,]),'SYMBOL':([0,2,4,5,6,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,],[7,7,-4,-5,16,-6,-10,16,-13,-14,16,-17,-18,16,16,16,16,16,-15,-7,-8,-9,-11,-12,-16,]),'MINUS':([6,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,],[11,19,-10,-13,-14,11,-17,-18,11,11,11,11,11,-15,19,19,-8,-9,-11,-12,-16,]),'LPAREN':([6,14,17,18,19,20,21,],[14,14,14,14,14,14,14,]),'NUMBER':([6,11,14,17,18,19,20,21,],[15,15,15,15,15,15,15,15,]),'EQUAL':([7,],[17,]),'PLUS':([9,10,12,13,15,16,22,23,24,25,26,27,28,29,],[18,-10,-13,-14,-17,-18,-15,18,18,-8,-9,-11,-12,-16,]),'RPAREN':([10,12,13,15,16,22,23,25,26,27,28,29,],[-10,-13,-14,-17,-18,-15,29,-8,-9,-11,-12,-16,]),'TIMES':([10,12,13,15,16,22,25,26,27,28,29,],[20,-13,-14,-17,-18,-15,20,20,-11,-12,-16,]),'DIVIDE':([10,12,13,15,16,22,25,26,27,28,29,],[21,-13,-14,-17,-18,-15,21,21,-11,-12,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,2,],[1,8,]),'statement':([0,2,],[2,2,]),'empty':([0,2,],[3,3,]),'p_statement':([0,2,],[4,4,]),'a_statement':([0,2,],[5,5,]),'expression':([6,14,17,],[9,23,24,]),'term':([6,14,17,18,19,],[10,10,10,25,26,]),'factor':([6,14,17,18,19,20,21,],[12,12,12,12,12,27,28,]),'num':([6,11,14,17,18,19,20,21,],[13,22,13,13,13,13,13,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statement statements','statements',2,'p_statements_1','sample.py',95),
  ('statements -> empty','statements',1,'p_statements_2','sample.py',98),
  ('empty -> <empty>','empty',0,'p_empty_1','sample.py',101),
  ('statement -> p_statement','statement',1,'p_statement_1','sample.py',104),
  ('statement -> a_statement','statement',1,'p_statement_2','sample.py',107),
  ('p_statement -> PRINT expression','p_statement',2,'p_pstatement_1','sample.py',110),
  ('a_statement -> SYMBOL EQUAL expression','a_statement',3,'p_astatement_1','sample.py',113),
  ('expression -> expression PLUS term','expression',3,'p_expression_1','sample.py',116),
  ('expression -> expression MINUS term','expression',3,'p_expression_2','sample.py',119),
  ('expression -> term','expression',1,'p_expression_3','sample.py',122),
  ('term -> term TIMES factor','term',3,'p_term_1','sample.py',125),
  ('term -> term DIVIDE factor','term',3,'p_term_2','sample.py',128),
  ('term -> factor','term',1,'p_term_3','sample.py',131),
  ('factor -> num','factor',1,'p_factor_1','sample.py',134),
  ('factor -> MINUS num','factor',2,'p_factor_2','sample.py',137),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_3','sample.py',140),
  ('num -> NUMBER','num',1,'p_num_1','sample.py',143),
  ('num -> SYMBOL','num',1,'p_num_2','sample.py',146),
]
